/*******************************************************************************
 * Qyotta UG (haftungsbeschränkt) (http://www.qyotta.de).
 * All rights reserved.
 * Copyright (c) 2012 Qyotta UG
 *******************************************************************************/
package de.qyotta.fourtytwocom.api.example.client.modules.dashboard;

import javax.inject.Inject;

import org.gwtbootstrap3.client.ui.Button;
import org.gwtbootstrap3.client.ui.Input;
import org.gwtbootstrap3.client.ui.html.Span;

import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ChangeEvent;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.KeyDownEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;

public class DashboardViewImpl extends DefaultView implements DashboardView {

   private static DashboardViewImplUiBinder uiBinder = GWT.create(DashboardViewImplUiBinder.class);

   interface DashboardViewImplUiBinder extends UiBinder<Widget, DashboardViewImpl> {
      // concrete implementation generated by GWT
   }

   private final Widget view;

   @UiField
   protected Input domain;

   @UiField
   protected Input username;

   @UiField
   protected Input password;

   @UiField
   protected Span resultingUri;

   @UiField
   protected Button saveButton;

   private Presenter presenter = Presenter.NULL;

   @Inject
   public DashboardViewImpl() {
      this.view = uiBinder.createAndBindUi(this);
   }

   @UiHandler("domain")
   void onKeyDown(final KeyDownEvent e) {
      presenter.onDomainChanged(domain.getValue());

   }

   @UiHandler("domain")
   void onKeyDown(final ChangeEvent e) {
      presenter.onDomainChanged(domain.getValue());
   }

   @UiHandler("saveButton")
   void onSaveButton(final ClickEvent clickEvent) {
      presenter.onSaveButton(domain.getValue(), username.getValue(), password.getValue());
   }

   @Override
   public Widget asWidget() {
      return view.asWidget();
   }

   @Override
   public void setPresenter(final Presenter presenter) {
      this.presenter = presenter;
   }

   @Override
   public void updateResultingUri(final String uri) {
      resultingUri.setText(uri);
   }

   @Override
   public String getDomain() {
      return domain.getValue();
   }
}