/*******************************************************************************
 * Qyotta UG (haftungsbeschränkt) (http://www.qyotta.de).
 * All rights reserved.
 * Copyright (c) 2012 Qyotta UG
 *******************************************************************************/
package de.qyotta.fourtytwocom.api.example.client.init;

import com.google.gwt.place.shared.PlaceHistoryMapper;
import com.google.gwt.place.shared.WithTokenizers;

import de.qyotta.fourtytwocom.api.example.client.modules.account.AccountPlace;
import de.qyotta.fourtytwocom.api.example.client.modules.dashboard.DashboardPlace;

// @formatter:off
@WithTokenizers({ 
   DashboardPlace.Tokenizer.class,
   AccountPlace.Tokenizer.class,
})
//@formatter:on
public interface AppPlaceHistoryMapper extends PlaceHistoryMapper {
   // concrete implementation is generated by GWT
}
