/*******************************************************************************
 * Qyotta UG (haftungsbeschränkt) (http://www.qyotta.de).
 * All rights reserved.
 * Copyright (c) 2012 Qyotta UG
 *******************************************************************************/
package de.qyotta.fourtytwocom.api.example.client.modules.account;

import javax.inject.Inject;

import org.gwtbootstrap3.client.ui.Button;

import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Widget;

public class AccountViewImpl implements AccountView {

   private static AccountViewImplUiBinder uiBinder = GWT.create(AccountViewImplUiBinder.class);

   interface AccountViewImplUiBinder extends UiBinder<Widget, AccountViewImpl> {
      // concrete implementation generated by GWT
   }

   private final Widget view;

   @UiField
   Button sendButton;

   private Presenter presenter = Presenter.NULL;

   @Inject
   public AccountViewImpl() {
      this.view = uiBinder.createAndBindUi(this);
   }

   @UiHandler("sendButton")
   void onSendButton(final ClickEvent clickEvent) {
      presenter.onSendButton();
   }

   @Override
   public Widget asWidget() {
      return view.asWidget();
   }

   @Override
   public void setPresenter(final Presenter presenter) {
      this.presenter = presenter;
   }
}